/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComicCard: typeof import('./src/components/ComicCard.vue')['default']
    FloatLabelInput: typeof import('./src/components/FloatLabelInput.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialog: typeof import('naive-ui')['NDialog']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEl: typeof import('naive-ui')['NEl']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputGroupLabel: typeof import('naive-ui')['NInputGroupLabel']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NProgress: typeof import('naive-ui')['NProgress']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NVirtualList: typeof import('naive-ui')['NVirtualList']
  }
}

// For TSX support
declare global {
  const ComicCard: typeof import('./src/components/ComicCard.vue')['default']
  const FloatLabelInput: typeof import('./src/components/FloatLabelInput.vue')['default']
  const NA: typeof import('naive-ui')['NA']
  const NAvatar: typeof import('naive-ui')['NAvatar']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NCheckbox: typeof import('naive-ui')['NCheckbox']
  const NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDialog: typeof import('naive-ui')['NDialog']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NEl: typeof import('naive-ui')['NEl']
  const NEmpty: typeof import('naive-ui')['NEmpty']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NInput: typeof import('naive-ui')['NInput']
  const NInputGroup: typeof import('naive-ui')['NInputGroup']
  const NInputGroupLabel: typeof import('naive-ui')['NInputGroupLabel']
  const NInputNumber: typeof import('naive-ui')['NInputNumber']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NModal: typeof import('naive-ui')['NModal']
  const NModalProvider: typeof import('naive-ui')['NModalProvider']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  const NPagination: typeof import('naive-ui')['NPagination']
  const NProgress: typeof import('naive-ui')['NProgress']
  const NRadioButton: typeof import('naive-ui')['NRadioButton']
  const NRadioGroup: typeof import('naive-ui')['NRadioGroup']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NTabPane: typeof import('naive-ui')['NTabPane']
  const NTabs: typeof import('naive-ui')['NTabs']
  const NVirtualList: typeof import('naive-ui')['NVirtualList']
}